bug to solve
<ipython-input-3-f9bb266f2bc5> in find_best_question(self, rows)
    130                     max_info_attenuation = temp_info_attenuation
    131                     best_question = q
--> 132         return max_info_attenuation, best_question
    133
    134     # === Input rows of data with attributes and labels ===

UnboundLocalError: local variable 'best_question' referenced before assignment

this might affect all of the 3 programs.
the error occured because there exists a question such that, after classifying rows according to this question, the gini info increased, So the best question is never updated.
Is it even possible?